name: Does it build and publish?

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Why are you triggering me?'
        required: false
        default: 'Test run'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build ${{ matrix.os }} - Bash
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - node: 12
            os: macos-latest
            siteUrl: SITEURL_MACOS
          - node: 12
            os: ubuntu-latest
            siteUrl: SITEURL_LINUX

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        registry-url: https://registry.npmjs.org/
  
    - run: npm i
      
    - run: npm start

    - run: npm link

    - run: | 
        git clone https://github.com/ValoIntranet/doctor-sample
        cd doctor-sample
        doctor publish -a password --username "${{ secrets.USERNAME }}" --password "${{ secrets.PASSWORD }}" -u "${{ secrets[matrix.siteUrl] }}" --cleanStart --confirm

  build_pwsh:
    name: Build windows-latest - powershell
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
  
    - run: npm i
      shell: powershell
      
    - run: npm start
      shell: powershell

    - run: npm link
      shell: powershell

    - run: | 
        git clone https://github.com/ValoIntranet/doctor-sample
        cd doctor-sample
        doctor publish -a password --username "${{ secrets.USERNAME }}" --password "${{ secrets.PASSWORD }}" -u "${{ secrets.SITEURL_WINDOWS_POWERSHELL }}" --cleanStart --confirm
      shell: powershell

  build_cmd:
    name: Build windows-latest - cmd
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
  
    - run: npm i
      shell: cmd
      
    - run: npm start
      shell: cmd

    - run: npm link
      shell: cmd

    - run: | 
        git clone https://github.com/ValoIntranet/doctor-sample
        cd doctor-sample
        doctor publish -a password --username "${{ secrets.USERNAME }}" --password "${{ secrets.PASSWORD }}" -u "${{ secrets.SITEURL_WINDOWS }}" --cleanStart --confirm
      shell: cmd

  screenshots:
    name: Take screenshots after publishing
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build, build_pwsh, build_cmd]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: |
        npm i playwright-chromium node-sp-auth@3
        node ./scripts/screenshots.js
      env:
        USER_NAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SITEURL_WINDOWS: ${{ secrets.SITEURL_WINDOWS }}
        SITEURL_WINDOWS_POWERSHELL: ${{ secrets.SITEURL_WINDOWS_POWERSHELL }}
        SITEURL_MACOS: ${{ secrets.SITEURL_MACOS }}
        SITEURL_LINUX: ${{ secrets.SITEURL_LINUX }}
    - uses: actions/upload-artifact@v2
      with:
        name: Screenshots
        path: screenshots/**/*.png
